version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/web_server/htdocs:/usr/share/nginx/html
      - /var/web_server/htdocs/default.conf:/etc/nginx/conf.d/default.conf
      - /var/web_server/htdocs/he/config/certs:/var/web_server/htdocs/he/config/certs
      - /var/web_server/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - web_network
    depends_on:
      - backend

  # Backend service
  backend:
    image: ghcr.io/teachbooks/he-backend:latest  # Fixed from nginx:alpine
    container_name: backend
    restart: always
    networks:
      - web_network
    volumes:
      - /var/web_server/saml/certs:/app/saml/certs:ro
    environment:
      - SECRET_KEY=${SECRET_KEY:-f7c518ccb0ce0dcfccdc85ff96d2700a5f6ec2a31f06a091df01c0bcb8d786be}

networks:
  web_network:
    driver: bridge