# .github/workflows/book-post-deploy.yml
name: Book Post-Deployment

on:
  workflow_run:
    workflows: ["call-deploy-book"]
    types:
      - completed

jobs:
  copy-to-server:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get workflow details
        id: workflow-details
        uses: actions/github-script@v6
        with:
          script: |
            const workflow_run_id = ${{ github.event.workflow_run.id }};
            console.log(`Workflow Run ID: ${workflow_run_id}`);
            
            // List artifacts from the workflow run
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: workflow_run_id
            });
            
            // Find the book artifact
            const artifactId = artifacts.data.artifacts.find(a => a.name === 'main').id;
            console.log(`Artifact ID: ${artifactId}`);
            
            return {
              artifact_id: artifactId,
              run_id: workflow_run_id
            };
      
      - name: Download artifact
        run: |
          # Create a temporary directory
          mkdir -p /tmp/book-download
          cd /tmp/book-download
          
          # Download the artifact using the GitHub API
          curl -L -o book.zip \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ fromJSON(steps.workflow-details.outputs.result).artifact_id }}/zip"
          
          # Unzip the downloaded file
          unzip book.zip -d extracted
          
          # Clean the existing book directory
          rm -rf /var/web_server/htdocs/book/*
          
          # Copy the extracted book to the web server
          cp -r extracted/* /var/web_server/htdocs/book/
          
          # Set proper permissions
          chmod -R 755 /var/web_server/htdocs/book/
          
          # Clean up
          cd /
          rm -rf /tmp/book-download
          
          echo "Book deployed successfully!"