name: Book Post-Deployment

on:
  workflow_run:
    workflows: ["call-deploy-book"]
    types:
      - completed

jobs:
  copy-to-server:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          
      - name: Find and deploy book content
        run: |
          # Debug information
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          
          # Try to find the book in various locations
          if [ -d "book/_build/html" ]; then
            BOOK_DIR="book/_build/html"
          elif [ -d "_build/html" ]; then
            BOOK_DIR="_build/html"
          else
            # Look for any _build/html directory
            BOOK_DIR=$(find . -path "*/_build/html" -type d | head -n 1)
          fi
          
          # If we found a book directory
          if [ -n "$BOOK_DIR" ]; then
            echo "Found book directory: $BOOK_DIR"
            # Create target directory
            mkdir -p /var/web_server/htdocs/book
            # Copy book content
            cp -r "$BOOK_DIR"/* /var/web_server/htdocs/book/
            # Set permissions
            chmod -R 755 /var/web_server/htdocs/book/
            echo "Book copied successfully!"
          else
            # If no book directory found, create a placeholder
            echo "Book directory not found, creating placeholder"
            mkdir -p /var/web_server/htdocs/book
            cat > /var/web_server/htdocs/book/index.html << 'EOHTML'
<!DOCTYPE html>
<html>
<head>
  <title>HE Staff Book</title>
  <style>
    body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
  </style>
</head>
<body>
  <h1>HE Staff Book</h1>
  <p>The book content will appear here after a successful build.</p>
</body>
</html>
EOHTML
            # Set permissions
            chmod -R 755 /var/web_server/htdocs/book/
            echo "Placeholder created successfully!"
          fi