name: Deploy and Build HE Website

on:
  workflow_run:
    workflows: ["call-deploy-book"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: call-deploy-book.yml
          workflow_conclusion: success
          name: github-pages
          path: download
          
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host jumphost
              HostName student-linux.tudelft.nl
              User ${{ secrets.JUMP_USER }}
              IdentityFile ~/.ssh/id_ed25519
            
            Host target
              HostName edu01.citg.tudelft.nl
              User ${{ secrets.SSH_USER }}
              ProxyJump jumphost
              IdentityFile ~/.ssh/id_ed25519


      - name: Test SSH Connection
        run: |
          # Test DNS resolution
          nslookup student-linux.tudelft.nl
          
          # Test basic connectivity
          ping -c 4 student-linux.tudelft.nl || true
          
          # Try SSH with verbose output
          ssh -vvv -o ConnectTimeout=30 ${{ secrets.JUMP_USER }}@student-linux.tudelft.nl 'echo test' || true

              
          
      - name: Deploy content and rebuild container
        run: |
          rsync -avz --delete \
            -e "ssh -J ${{ secrets.JUMP_USER }}@student-linux.tudelft.nl" \
            download/ \
            ${{ secrets.SSH_USER }}@edu01.citg.tudelft.nl:/tmp/he_update/

          ssh -J ${{ secrets.JUMP_USER }}@student-linux.tudelft.nl ${{ secrets.SSH_USER }}@edu01.citg.tudelft.nl '
            sudo rsync -avz /tmp/he_update/ /var/web_server/htdocs/he/ &&
            sudo chown -R root:root /var/web_server/htdocs/he &&
            sudo chmod 755 /var/web_server/htdocs/he &&
            cd /var/web_server/htdocs/he &&
            sudo docker compose down &&
            sudo docker compose up -d --build
          '