name: Deploy Book to Server

on:
  push:
    branches:
      - '**'
    paths:
      - 'book/**'
      - '.github/workflows/deploy-book-to-server.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the book
        run: teachbooks build book

      - name: Upload built book as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: built-book
          path: book/_build/html/

      - name: Rsync built book to server
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -J ${{ secrets.SERVER_BASTION }}" book/_build/html/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp/book_content_${{ github.ref_name }}/

      - name: Run deploy-book.sh on server
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -J ${{ secrets.SERVER_BASTION }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "/var/web_server/deploy-book.sh '${{ github.ref_name }}' '/tmp/book_content_${{ github.ref_name }}'"
